// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSgQNPHV3yztdr2O_u7PKIX2Odj1n5ryo',
    appId: '1:592013171584:web:f4cc5347e67126e1eabf65',
    messagingSenderId: '592013171584',
    projectId: 'mynotes-razvan',
    authDomain: 'mynotes-razvan.firebaseapp.com',
    storageBucket: 'mynotes-razvan.appspot.com',
    measurementId: 'G-RZ68V23X0Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl5UM5QNaLQrOGESQIciB1ZyW_nPA2L0U',
    appId: '1:592013171584:android:5a318b492686f029eabf65',
    messagingSenderId: '592013171584',
    projectId: 'mynotes-razvan',
    storageBucket: 'mynotes-razvan.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrPqoCEUbj3BwZdvHPi_x0628MEIlhFxw',
    appId: '1:592013171584:ios:f066c570eb05445ceabf65',
    messagingSenderId: '592013171584',
    projectId: 'mynotes-razvan',
    storageBucket: 'mynotes-razvan.appspot.com',
    iosClientId:
        '592013171584-8vl9ppusu8c7f0n1puhf531juom6ocss.apps.googleusercontent.com',
    iosBundleId: 'se.pixolity.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrPqoCEUbj3BwZdvHPi_x0628MEIlhFxw',
    appId: '1:592013171584:ios:f066c570eb05445ceabf65',
    messagingSenderId: '592013171584',
    projectId: 'mynotes-razvan',
    storageBucket: 'mynotes-razvan.appspot.com',
    iosClientId:
        '592013171584-8vl9ppusu8c7f0n1puhf531juom6ocss.apps.googleusercontent.com',
    iosBundleId: 'se.pixolity.mynotes',
  );
}
